//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources.uk_UA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResources.uk_UA.uk-UA", typeof(uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати рядок.
        /// </summary>
        public static string AddNewBarButton_Caption {
            get {
                return ResourceManager.GetString("AddNewBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нелогічна поведінка була знайдена в програмі
        ///Повідомлення вже вислано на пошту
        ///Будь-ласка перезапустіть програму!.
        /// </summary>
        public static string Application_Logic_Error {
            get {
                return ResourceManager.GetString("Application_Logic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатково.
        /// </summary>
        public static string ApplicationMenu_Caption {
            get {
                return ResourceManager.GetString("ApplicationMenu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка недоступна. Натисніть
        ///&quot;OK&quot; - постійно провіряти доступність сайту,
        ///або &quot;Скасувати&quot; - щоб відмінити..
        /// </summary>
        public static string AvailabilityError_Message {
            get {
                return ResourceManager.GetString("AvailabilityError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт клієнтів.
        /// </summary>
        public static string BarButtonItemImport_Caption {
            get {
                return ResourceManager.GetString("BarButtonItemImport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string BarButtonItemSetup_Caption {
            get {
                return ResourceManager.GetString("BarButtonItemSetup_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string ButtonCancel_Text {
            get {
                return ResourceManager.GetString("ButtonCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити процес.
        /// </summary>
        public static string ButtonCancelAction_Text {
            get {
                return ResourceManager.GetString("ButtonCancelAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити проксі.
        /// </summary>
        public static string ButtonLoadProxies_Text {
            get {
                return ResourceManager.GetString("ButtonLoadProxies_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string ButtonOk_Text {
            get {
                return ResourceManager.GetString("ButtonOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустити реєстрацію.
        /// </summary>
        public static string ButtonRegistry_Text {
            get {
                return ResourceManager.GetString("ButtonRegistry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string CancelBarButton_Caption {
            get {
                return ResourceManager.GetString("CancelBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string colBirthday {
            get {
                return ResourceManager.GetString("colBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К-ть дітей у паспорті батьків.
        /// </summary>
        public static string colChildsCount {
            get {
                return ResourceManager.GetString("colChildsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата закінчення дії паспорту.
        /// </summary>
        public static string colEndPassportDate {
            get {
                return ResourceManager.GetString("colEndPassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string colLastName {
            get {
                return ResourceManager.GetString("colLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string colName {
            get {
                return ResourceManager.GetString("colName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № квитанції.
        /// </summary>
        public static string colNumberOfReceipt {
            get {
                return ResourceManager.GetString("colNumberOfReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість заявників.
        /// </summary>
        public static string colPeopleCount {
            get {
                return ResourceManager.GetString("colPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація З.
        /// </summary>
        public static string colRegistryFom {
            get {
                return ResourceManager.GetString("colRegistryFom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryFom.
        /// </summary>
        public static string colRegistryFom_DataColumn_Name {
            get {
                return ResourceManager.GetString("colRegistryFom_DataColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата повинна бути скоріше за &quot;Реєстрація До&quot;.
        /// </summary>
        public static string colRegistryFom_ValidationError {
            get {
                return ResourceManager.GetString("colRegistryFom_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час реєстрації.
        /// </summary>
        public static string colRegistryTime {
            get {
                return ResourceManager.GetString("colRegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація До.
        /// </summary>
        public static string colRegistryTo {
            get {
                return ResourceManager.GetString("colRegistryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryTo.
        /// </summary>
        public static string colRegistryTo_DataColumn_Name {
            get {
                return ResourceManager.GetString("colRegistryTo_DataColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата повинна бути пізніше за &quot;Реєстрація З&quot;.
        /// </summary>
        public static string colRegistryTo_ValidationError {
            get {
                return ResourceManager.GetString("colRegistryTo_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата повернення.
        /// </summary>
        public static string colReturnData {
            get {
                return ResourceManager.GetString("colReturnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string colStatus {
            get {
                return ResourceManager.GetString("colStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрацію завершено.
        /// </summary>
        public static string Complete_Registration {
            get {
                return ResourceManager.GetString("Complete_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопіювати ключ.
        /// </summary>
        public static string CopyBarButton_Caption {
            get {
                return ResourceManager.GetString("CopyBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовник.
        /// </summary>
        public static string CustomerBarEdit_Caption {
            get {
                return ResourceManager.GetString("CustomerBarEdit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замовники.
        /// </summary>
        public static string CustomersBarButton_Caption {
            get {
                return ResourceManager.GetString("CustomersBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата не відповідає діапазону 
        ///{0}.
        /// </summary>
        public static string DateIncorrect_Message {
            get {
                return ResourceManager.GetString("DateIncorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрано {0}
        ///як дату рестрації.
        /// </summary>
        public static string DateSelected_Message {
            get {
                return ResourceManager.GetString("DateSelected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата для реєстрації є доступна
        ///{0}.
        /// </summary>
        public static string DateСorrect_Message {
            get {
                return ResourceManager.GetString("DateСorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити всі рядки.
        /// </summary>
        public static string DeleteAllBarButton_Caption {
            get {
                return ResourceManager.GetString("DeleteAllBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити рядок.
        /// </summary>
        public static string DeleteBarButton_Caption {
            get {
                return ResourceManager.GetString("DeleteBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операції з базою.
        /// </summary>
        public static string EditGroup_title {
            get {
                return ResourceManager.GetString("EditGroup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команди.
        /// </summary>
        public static string EditPage_Title {
            get {
                return ResourceManager.GetString("EditPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В програмі була згенерована помилка 
        ///яка не була належним чином оброблена. 
        ///Будь-ласка пришліть детальний опис 
        ///ваших дій  і опис помилки що є внизу..
        /// </summary>
        public static string ExceptionHanler_Text {
            get {
                return ResourceManager.GetString("ExceptionHanler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string ExceptionHanler_Title {
            get {
                return ResourceManager.GetString("ExceptionHanler_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка випевніть капчу
        ///Та виберіть дату реєстрації
        ///Після цьго натисніть ТУТ!!!.
        /// </summary>
        public static string Fill_Calendar_And_Captcha {
            get {
                return ResourceManager.GetString("Fill_Calendar_And_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрацію завершено, 
        ///випевніть капчу і виберіть дату.
        /// </summary>
        public static string FillCaptchaAndComplete {
            get {
                return ResourceManager.GetString("FillCaptchaAndComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Випевніть капчу і натисніть ТУТ..
        /// </summary>
        public static string FillCaptchaAndPress {
            get {
                return ResourceManager.GetString("FillCaptchaAndPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийшов термін дії активації ключа. 
        ///Для подальшого використання звернітся до дистриб&apos;ютора..
        /// </summary>
        public static string Key_NotActive {
            get {
                return ResourceManager.GetString("Key_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей ключ уже використовуєтся 
        ///іншим комп&apos;ютером.
        /// </summary>
        public static string Key_Used {
            get {
                return ResourceManager.GetString("Key_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний ключ не знайдено!.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматично оновлятись.
        /// </summary>
        public static string Label_AutoUpdate {
            get {
                return ResourceManager.GetString("Label_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевіряти на наявність оновлень.
        /// </summary>
        public static string Label_ChekForUpdate {
            get {
                return ResourceManager.GetString("Label_ChekForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL для провірки доступності сайту.
        /// </summary>
        public static string lblAvailabilityUrl {
            get {
                return ResourceManager.GetString("lblAvailabilityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна команди.
        /// </summary>
        public static string lblCancelGroup {
            get {
                return ResourceManager.GetString("lblCancelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть проксі (Click).
        /// </summary>
        public static string lblChooseProxies {
            get {
                return ResourceManager.GetString("lblChooseProxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані клієнтів.
        /// </summary>
        public static string lblClientDataGroup {
            get {
                return ResourceManager.GetString("lblClientDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрити бравзер після закінчення?.
        /// </summary>
        public static string lblCloseBrowser {
            get {
                return ResourceManager.GetString("lblCloseBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email для відправки реєстрації.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервісний центр:.
        /// </summary>
        public static string lblServiceCenter {
            get {
                return ResourceManager.GetString("lblServiceCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Візова категорія:.
        /// </summary>
        public static string lblVisaCategory {
            get {
                return ResourceManager.GetString("lblVisaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструвати.
        /// </summary>
        public static string LicenseForm_RegButton {
            get {
                return ResourceManager.GetString("LicenseForm_RegButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка введіть ліцензійний ключ.
        /// </summary>
        public static string LicenseForm_Title {
            get {
                return ResourceManager.GetString("LicenseForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ліцензії.
        /// </summary>
        public static string LicensesBarButton_Caption {
            get {
                return ResourceManager.GetString("LicensesBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основні таблиці.
        /// </summary>
        public static string MainGroup_Title {
            get {
                return ResourceManager.GetString("MainGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиці.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть Національніть-.
        /// </summary>
        public static string Nationality_NullText {
            get {
                return ResourceManager.GetString("Nationality_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Національність.
        /// </summary>
        public static string Nationality_Text {
            get {
                return ResourceManager.GetString("Nationality_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вільних дат не має.
        /// </summary>
        public static string NoDate_Message {
            get {
                return ResourceManager.GetString("NoDate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка виберіть Excel документ 
        ///з даними по шаблону.
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операції з таблицьою.
        /// </summary>
        public static string OperationsGroup_Title {
            get {
                return ResourceManager.GetString("OperationsGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Польський візовий центр доступний.
        /// </summary>
        public static string PageAvailable {
            get {
                return ResourceManager.GetString("PageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт недоступний.
        /// </summary>
        public static string PageNotAvailable {
            get {
                return ResourceManager.GetString("PageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password_Text {
            get {
                return ResourceManager.GetString("Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        public static string RefreshBarButton_Caption {
            get {
                return ResourceManager.GetString("RefreshBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Час Реєстрації-.
        /// </summary>
        public static string RegistryTime_NullText {
            get {
                return ResourceManager.GetString("RegistryTime_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторно запускати при помилці.
        /// </summary>
        public static string RepeatIfCrash_Text {
            get {
                return ResourceManager.GetString("RepeatIfCrash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string SaveBarButton_Caption {
            get {
                return ResourceManager.GetString("SaveBarButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати пошуку.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не відповідає. Щоб поторити
        /// спробу запустіть перевірку знову!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть ППВА-.
        /// </summary>
        public static string ServiceCenter_NullText {
            get {
                return ResourceManager.GetString("ServiceCenter_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступні скіни до вибору.
        /// </summary>
        public static string SkinGroup_Title {
            get {
                return ResourceManager.GetString("SkinGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кастомізація.
        /// </summary>
        public static string SkinPage_Title {
            get {
                return ResourceManager.GetString("SkinPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть Статус-.
        /// </summary>
        public static string Status_NullText {
            get {
                return ResourceManager.GetString("Status_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string ToggleSwitch_OffText {
            get {
                return ResourceManager.GetString("ToggleSwitch_OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string ToggleSwitch_OnText {
            get {
                return ResourceManager.GetString("ToggleSwitch_OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка виберіть замовника.
        /// </summary>
        public static string ValidationError_Message_Customer {
            get {
                return ResourceManager.GetString("ValidationError_Message_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка випевніть візовий ценрт
        /// і візову категорію.
        /// </summary>
        public static string ValidationError_Message_FirstPart {
            get {
                return ResourceManager.GetString("ValidationError_Message_FirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це поле повинно містити в собі значення.
        /// </summary>
        public static string ValidationError_Message_NullText {
            get {
                return ResourceManager.GetString("ValidationError_Message_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка випевніть пошту в опціях.
        /// </summary>
        public static string ValidationError_Message_Option_Email {
            get {
                return ResourceManager.GetString("ValidationError_Message_Option_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка випевніть пароль в опціях.
        /// </summary>
        public static string ValidationError_Message_Option_Password {
            get {
                return ResourceManager.GetString("ValidationError_Message_Option_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка перевірте введені вами дані.
        /// </summary>
        public static string ValidationError_Message_SecondPart {
            get {
                return ResourceManager.GetString("ValidationError_Message_SecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валідація не пройдена.
        /// </summary>
        public static string ValidationError_Title {
            get {
                return ResourceManager.GetString("ValidationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть візову категорію-.
        /// </summary>
        public static string VisaCategory_NullText {
            get {
                return ResourceManager.GetString("VisaCategory_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка не загрузила всі компоненти.
        /// </summary>
        public static string WebPage_StillNotLoaded {
            get {
                return ResourceManager.GetString("WebPage_StillNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер недоступний.
        ///Сторінка буде перезагружена!.
        /// </summary>
        public static string WebPage_WillBeReloaded {
            get {
                return ResourceManager.GetString("WebPage_WillBeReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачекайте будь ласка закінчення попередньої операції.
        /// </summary>
        public static string Worker_IsBusy {
            get {
                return ResourceManager.GetString("Worker_IsBusy", resourceCulture);
            }
        }
    }
}
